### ISSUE TITLE
Operator pods restarts when GUI node is shutdown

### ISSUE THREAD

**Issue by saurabhwani5** [IBM/ibm-spectrum-scale-csi#1003]
## Describe the bug
Operator pods restarts multiple times when GUI node is shutdown 

## How to Reproduce?

1. Shutdown the GUI node 
```
[root@csi-518-master pr1002]# ssh root@csi-518-scalegui
ssh: connect to host csi-518-scalegui port 22: No route to host
```

2. Install CSI 2.10.0 (Dev)
```
[root@csi-518-master pr1002]# oc apply -f ibm-spectrum-scale-csi-operator.yaml
deployment.apps/ibm-spectrum-scale-csi-operator created
clusterrole.rbac.authorization.k8s.io/ibm-spectrum-scale-csi-operator created
clusterrolebinding.rbac.authorization.k8s.io/ibm-spectrum-scale-csi-operator created
serviceaccount/ibm-spectrum-scale-csi-operator created
customresourcedefinition.apiextensions.k8s.io/csiscaleoperators.csi.ibm.com created
[root@csi-518-master pr1002]# oc apply -f csiscaleoperators.csi.ibm.com_cr.yaml
csiscaleoperator.csi.ibm.com/ibm-spectrum-scale-csi created
[root@csi-518-master pr1002]# oc describe pod | grep quay
    Image:         quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator@sha256:3e5b73cfbffa72d9cdf71fe369522cd2c9841970372715896e99b733d96eaed6
    Image ID:      quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator@sha256:3e5b73cfbffa72d9cdf71fe369522cd2c9841970372715896e99b733d96eaed6
      CSI_DRIVER_IMAGE:      quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver@sha256:ee9bd3e431cf0d3fb1e407a6e2ed51d6be957dd1445c2cd88f329cbb5b1ea494
  Normal  Pulling    17s   kubelet            Pulling image "quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator@sha256:3e5b73cfbffa72d9cdf71fe369522cd2c9841970372715896e99b733d96eaed6"
  Normal  Pulled     11s   kubelet            Successfully pulled image "quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator@sha256:3e5b73cfbffa72d9cdf71fe369522cd2c9841970372715896e99b733d96eaed6" in 6.126035334s (6.126234235s including waiting
```
3. check the Operator pod 
```
[root@csi-518-master pr1002]# oc get pods -w
NAME                                               READY   STATUS   RESTARTS      AGE
ibm-spectrum-scale-csi-operator-79c7f656d8-4jxnw   0/1     Error    1 (19s ago)   45s
ibm-spectrum-scale-csi-operator-79c7f656d8-4jxnw   0/1     CrashLoopBackOff   1 (1s ago)    46s
ibm-spectrum-scale-csi-operator-79c7f656d8-4jxnw   0/1     Running            2 (16s ago)   61s
[root@csi-518-master pr1002]# oc get cso
NAME                     VERSION   SUCCESS
ibm-spectrum-scale-csi   2.10.0    Unknown
```
4. Check Operator Logs :
```
2023-08-23T11:08:04.569Z	DEBUG	csiscaleoperator_controller.Reconcile	Updated resource status.	{"Status": {"versions":[{"name":"ibm-spectrum-scale-csi","version":"2.10.0"}],"conditions":[{"type":"Success","status":"Unknown","lastTransitionTime":"2023-08-23T11:08:03Z","reason":"Unknown","message":""}]}}
2023-08-23T11:08:04.569Z	INFO	Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference	{"controller": "csiscaleoperator", "controllerGroup": "csi.ibm.com", "controllerKind": "CSIScaleOperator", "CSIScaleOperator": {"name":"ibm-spectrum-scale-csi","namespace":"ibm-spectrum-scale-csi-driver"}, "namespace": "ibm-spectrum-scale-csi-driver", "name": "ibm-spectrum-scale-csi", "reconcileID": "144a613d-30a6-411e-8c90-1cf088b2692d"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x156c5d0]

goroutine 261 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x17122a0, 0x2734870})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin/connectors.(*SpectrumRestV2).doHTTP(0xc000364140, {0x1b80798, 0xc0001b2120}, {0x191433e, 0x14}, {0x19020ce, 0x3}, {0x162fd80, 0xc000660840}, {0x0, ...})
	/go/pkg/mod/github.com/!i!b!m/ibm-spectrum-scale-csi/driver@v0.0.0-20230529112832-85319addc49a/csiplugin/connectors/rest_v2.go:1025 +0x970
github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin/connectors.(*SpectrumRestV2).GetClusterId(0x17032a0?, {0x1b80798, 0xc0001b2120})
	/go/pkg/mod/github.com/!i!b!m/ibm-spectrum-scale-csi/driver@v0.0.0-20230529112832-85319addc49a/csiplugin/connectors/rest_v2.go:191 +0x173
github.com/IBM/ibm-spectrum-scale-csi/operator/controllers.(*CSIScaleOperatorReconciler).handleSpectrumScaleConnectors(0xc000465b60, 0xc000116060, 0x0, 0x0)
	/workspace/controllers/csiscaleoperator_controller.go:1865 +0x457
github.com/IBM/ibm-spectrum-scale-csi/operator/controllers.(*CSIScaleOperatorReconciler).Reconcile(0xc000465b60, {0x1b80808, 0xc000307530}, {{{0xc0005a64c0?, 0xc000182b60?}, {0xc00002c750?, 0x40dfa7?}}})
	/workspace/controllers/csiscaleoperator_controller.go:300 +0xa6f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1b80808?, {0x1b80808?, 0xc000307530?}, {{{0xc0005a64c0?, 0x1697120?}, {0xc00002c750?, 0x0?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000140aa0, {0x1b80760, 0xc00054eff0}, {0x176cde0?, 0xc00059d820?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323 +0x377
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000140aa0, {0x1b80760, 0xc00054eff0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:231 +0x587
```
## Expected behavior
Operator pod shouldn't restart when GUI node is shutdown

**Comment by badri-pathak** [comment]
@saurabhwani5 This issue has been addressed in the same PR. Please have a look.
[https://github.com/IBM/ibm-spectrum-scale-csi/pull/1002](https://github.com/IBM/ibm-spectrum-scale-csi/pull/1002)

**Comment by amdabhad** [comment]
Fixed in dev branch, please verify.

**Comment by saurabhwani5** [comment]
Verified in #1002  , Thank You for fix
