### ISSUE TITLE
CSI driver crashes while checking gpfs version for snapshot. 

### ISSUE THREAD

**Issue by vrushch** [IBM/ibm-spectrum-scale-csi#431]
**Describe the bug**
CSI driver crashes while checking gpfs version for snapshot.  
GUI version is 
```
{
  "info" : {
    "name" : "Spectrum Scale REST Management",
    "restApiVersion" : "2.2.0",
    "serverVersion" : "5.1.1.1-developer build",
    "paths" : {
      "/access" : [ "POST", "GET" ],
```

Logs from driver pod
```

I0625 17:44:35.663249       1 utils.go:57] GRPC response: name:"spectrumscale.csi.ibm.com" vendor_version:"2.2.0"
I0625 17:44:35.664102       1 utils.go:51] GRPC call: /csi.v1.Controller/CreateSnapshot
I0625 17:44:35.664117       1 utils.go:52] GRPC request: source_volume_id:"1925837219448245938;0A0B55AC:60704F6C;filesetName=pvc-b0f69b5f-170a-4437-8084-43fc142c654c;path=/ibm/gpfs0/spectrum-scale-csi-volume-store/.volumes/pvc-b0f69b5f-170a-4437-8084-43fc142c654c" name:"snapshot-70d64205-fb29-4d28-b95a-4e05248a228c"
I0625 17:44:35.664219       1 controllerserver.go:1101] CreateSnapshot - create snapshot req: source_volume_id:"1925837219448245938;0A0B55AC:60704F6C;filesetName=pvc-b0f69b5f-170a-4437-8084-43fc142c654c;path=/ibm/gpfs0/spectrum-scale-csi-volume-store/.volumes/pvc-b0f69b5f-170a-4437-8084-43fc142c654c" name:"snapshot-70d64205-fb29-4d28-b95a-4e05248a228c"
I0625 17:45:31.470244       1 gpfs.go:132] gpfs ValidateControllerServiceRequest
I0625 17:45:31.470270       1 rest_v2.go:183] rest_v2 GetScaleVersion
I0625 17:45:31.470281       1 http_utils.go:60] http_utils FormatURL. url: https://csiscale-scalegui.fyre.ibm.com:443/
I0625 17:45:31.470296       1 rest_v2.go:774] rest_v2 doHTTP. endpoint: https://csiscale-scalegui.fyre.ibm.com:443/scalemgmt/v2/info, method: GET, param: <nil>
I0625 17:45:31.470307       1 http_utils.go:74] http_utils HttpExecuteUserAuth. type: GET, url: https://csiscale-scalegui.fyre.ibm.com:443/scalemgmt/v2/info, user: csiuser
I0625 17:45:31.500214       1 http_utils.go:44] http_utils UnmarshalResponse. response: &{0x59fcc0 0xc0001031c0 0x6cf760}
I0625 17:45:31.500574       1 rest_v2.go:43] rest_v2 isStatusOK. statusCode: 200
panic: runtime error: index out of range [1] with length 1

goroutine 20 [running]:
github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin.(*ScaleControllerServer).checkSnapshotSupport(0xc00000e378, 0xa330e0, 0xc000102900, 0xa330e0, 0xc000102900)
        /go/src/github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin/controllerserver.go:650 +0x345
github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin.(*ScaleControllerServer).CreateSnapshot(0xc00000e378, 0xa2bce0, 0xc0002046f0, 0xc000216550, 0xc00000e378, 0xca7766, 0xc00010fea0)
        /go/src/github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin/controllerserver.go:1132 +0x23d
github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateSnapshot_Handler.func1(0xa2bce0, 0xc0002046f0, 0x9538e0, 0xc000216550, 0xc00004b9b8, 0x1, 0x1, 0x30)
        /go/pkg/mod/github.com/container-storage-interface/spec@v1.1.0/lib/go/csi/csi.pb.go:5091 +0x89
github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin.logGRPC(0xa2bce0, 0xc0002046f0, 0x9538e0, 0xc000216550, 0xc00020ea80, 0xc00020eaa0, 0xc00006ba48, 0x59f546, 0x93d6c0, 0xc0002046f0)
        /go/src/github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin/utils.go:53 +0x10b
github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateSnapshot_Handler(0x9722a0, 0xc00000e378, 0xa2bce0, 0xc0002046f0, 0xc00025a0c0, 0x9ae8a8, 0xa2bce0, 0xc0002046f0, 0xc00025c000, 0xee)
        /go/pkg/mod/github.com/container-storage-interface/spec@v1.1.0/lib/go/csi/csi.pb.go:5093 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001e02c0, 0xa30180, 0xc000001c80, 0xc00022e100, 0xc000165f50, 0xcfb7c0, 0x0, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:995 +0x482
google.golang.org/grpc.(*Server).handleStream(0xc0001e02c0, 0xa30180, 0xc000001c80, 0xc00022e100, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:1275 +0xd34
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0001d6970, 0xc0001e02c0, 0xa30180, 0xc000001c80, 0xc00022e100)
        /go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:710 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:708 +0xa5
```
specifically look out for 
```
I0625 17:45:31.500574       1 rest_v2.go:43] rest_v2 isStatusOK. statusCode: 200
panic: runtime error: index out of range [1] with length 1
```
**To Reproduce**
1. make gui server version 5.1.1.1-developer build
2. create volumesnapshot
3. driver pods go to error state 

**Expected behavior**
CSI driver should not crash and volumesnapshot should be in readytouse true state

**Environment**
Please run the following an paste your output here:
``` bash
# Developement
operator-sdk version 
go version

# Deployment
[root@csiscale-master ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
[root@csiscale-master ~]#

[root@csiscale-scalegui ~]# rpm -qa | grep gpfs
gpfs.base-5.1.1-0.x86_64
gpfs.compression-5.1.1-0.x86_64
gpfs.msg.en_US-5.1.1-0.noarch
gpfs.gss.pmcollector-5.1.1-0.el7.x86_64
gpfs.adv-5.1.1-0.x86_64
gpfs.crypto-5.1.1-0.x86_64
gpfs.gpl-5.1.1-0.noarch
gpfs.docs-5.1.1-0.noarch
gpfs.afm.cos-1.0.0-1.x86_64
gpfs.java-5.1.1-0.x86_64
gpfs.gui-5.1.1-0.noarch
gpfs.librdkafka-5.1.1-0.x86_64
gpfs.bda-integration-1.0.3-0.noarch
gpfs.license.adv-5.1.1-0.x86_64
gpfs.gskit-8.0.55-19.x86_64
gpfs.gss.pmsensors-5.1.1-0.el7.x86_64
[root@csiscale-scalegui ~]#

```
**Screenshots**

**Additional context**

**Comment by deeghuge** [comment]
Hi @madhuthorat , Please check this one

**Comment by madhuthorat** [comment]
@vrushch Is "5.1.1.1-developer" in the right format for Spectrum Scale version ?
So far have seen Spectrum Scale versions in the format like "5.1.1-1xxxxxx", here notice the character '-'. The CSI code does version check with the assumption that version would be formatted like:
[root@csiscale-scalegui ~]# rpm -qa | grep gpfs
gpfs.base-**5.1.1-0**.x86_64

**Comment by vrushch** [comment]
Hi Madhu,
    5.1.1.1-developer was the version installed by deepak on gui node.
@deeghuge , can you add something to above ?

**Comment by deeghuge** [comment]
Hi Madhu, We have consider this as invalid input and return the error rather than crashing the driver pod

**Comment by madhuthorat** [comment]
This is fixed in latest code. Please verify.

**Comment by deeghuge** [comment]
Please reopen if required
