### ISSUE TITLE
Pods going into Crashloopback state, on stopping the gpfsgui for remote gui node.

### ISSUE THREAD

**Issue by monimeht** [IBM/ibm-spectrum-scale-csi#767]
## Describe the bug
Pods going into Crashloopback state, on making the gpfsgui stop for remote cluster. 

## How to Reproduce?
Below are the steps

1. Stop gpfsgui by executing "systemctl stop gpfsgui" on gui node of Remote cluster.
2. Create PVC.
3. Observe pods. 
```
root@monica-ubu-master:~/yaml# kubectl get pods -n ibm-spectrum-scale-csi-driver
NAME                                                  READY   STATUS             RESTARTS         AGE
ibm-spectrum-scale-csi-8w7r7                          3/3     Running            0                100m
ibm-spectrum-scale-csi-attacher-58b7c87cdd-28mlw      0/1     CrashLoopBackOff   22 (3m57s ago)   110m
ibm-spectrum-scale-csi-attacher-58b7c87cdd-h8dx4      1/1     Running            1 (100m ago)     110m
ibm-spectrum-scale-csi-jt8r6                          2/3     CrashLoopBackOff   18 (32s ago)     100m
ibm-spectrum-scale-csi-operator-6856bdbcc8-5kpnp      1/1     Running            0                111m
ibm-spectrum-scale-csi-provisioner-789cbb8748-6995c   0/1     CrashLoopBackOff   22 (3m17s ago)   110m
ibm-spectrum-scale-csi-resizer-f88ff77b-kv86s         0/1     CrashLoopBackOff   22 (2m17s ago)   110m
ibm-spectrum-scale-csi-snapshotter-75b545fbd5-ndhf4   0/1     CrashLoopBackOff   22 (4m17s ago)   110m
```

## Expected behavior
Pods of Primary Cluster should be in running state, on stopping the gpfsgui of remote gui node.

### Data Collection and Debugging

Environmental output

```
root@monica-ubu-master:~/yaml# oc get cso
NAME                     VERSION   SUCCESS
ibm-spectrum-scale-csi   2.7.0     True
```
2. GUI nodes of remote cluster
      restApi:
       - guiHost: "10.11.24.115"
       - guiHost: "10.11.25.26"
       - guiHost: "10.11.25.24"
3. Image used
value: quay.io/amdabhad/csi-driver-gui-ha:070722

Find attached the logs.

[podcrashbugs.txt](https://github.com/IBM/ibm-spectrum-scale-csi/files/9111795/podcrashbugs.txt)

DRIVER POD LOGS

Driver pod logs :
```

I0714 11:26:07.065189       1 rest_v2.go:693] rest_v2 ListFileset. filesystem: fs1, fileset: spectrum-scale-csi-volume-store
I0714 11:26:07.065209       1 rest_v2.go:999] rest_v2 doHTTP: urlSuffix: scalemgmt/v2/filesystems/fs1/filesets/spectrum-scale-csi-volume-store, method: GET, param: <nil>
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin/connectors.(*spectrumRestV2).doHTTP(0xc0000ba8c0, {0xc0000ce280, 0x45}, {0x8e743e, 0x3}, {0x82b460, 0xc0000bb040}, {0x0, 0x0})
        /go/src/github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin/connectors/rest_v2.go:1000 +0xb74
github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin/connectors.(*spectrumRestV2).ListFileset(_, {_, _}, {_, _})
        /go/src/github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin/connectors/rest_v2.go:698 +0x205
github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin.(*ScaleDriver).CreatePrimaryFileset(0x8ea548, {0x9aef10, 0xc0000ba8c0}, {0xc0000c32ec, 0x3}, {0xc000218428, 0x8}, {0x8f9866, 0x1f}, {0x0, ...})
        /go/src/github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin/gpfs.go:381 +0x1cd
github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin.(*ScaleDriver).PluginInitialize(0x97)
        /go/src/github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin/gpfs.go:340 +0x10c5
github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin.(*ScaleDriver).SetupScaleDriver(0xc00012a1e0, {0x8f52f2, 0xc0000de640}, {0x8e7e20, 0xc000135e70}, {0x7fff4c177c65, 0x0})
        /go/src/github.com/IBM/ibm-spectrum-scale-csi/driver/csiplugin/gpfs.go:199 +0x1a5
main.handle()
        /go/src/github.com/IBM/ibm-spectrum-scale-csi/driver/cmd/ibm-spectrum-scale-csi/main.go:75 +0x51
main.main()
        /go/src/github.com/IBM/ibm-spectrum-scale-csi/driver/cmd/ibm-spectrum-scale-csi/main.go:69 +0x45d
```

[podcrashbugs.txt](https://github.com/IBM/ibm-spectrum-scale-csi/files/9111795/podcrashbugs.txt)

Note : See [labels](https://github.com/IBM/ibm-spectrum-scale-csi/labels) for the labels

**Comment by amdabhad** [comment]
This is fixed in new build:  quay.io/amdabhad/csi-driver-gui-ha:140722

**Comment by monimeht** [comment]
Validated the issue on build "quay.io/amdabhad/csi-driver-gui-ha:140722", pods does'nt goes into Crashloopback and remains in Running state. 
Closing the Issue.
