### ISSUE TITLE
CSI upgrade from 2.9.0 to CSI 2.10.0(dev) is broken 

### ISSUE THREAD

**Issue by Jainbrt** [IBM/ibm-spectrum-scale-csi#961]
## Describe the bug
CSI upgrade from 2.9.0 to CSI 2.10.0(dev) is broken 

## How to Reproduce?
Please list the steps to help development teams reproduce the behavior

1. Upgraded from 2.9.0 to CSI 2.10.0(dev)

```
2023-04-10T13:26:57.889Z        DEBUG   csiscaleoperator_controller.Reconcile   Updated resource status.        {"Status": {"versions":[{"name":"ibm-spectrum-scale-csi","version":"2.10.0"}],"conditions":[{"type":"Success","status":"Unknown","lastTransitionTime":"2023-04-10T13:26:57Z","reason":"Unknown","message":""}]}}
2023-04-10T13:26:57.889Z        INFO    Observed a panic in reconciler: reflect: slice length out of range in SetLen    {"controller": "csiscaleoperator", "controllerGroup": "csi.ibm.com", "controllerKind": "CSIScaleOperator", "CSIScaleOperator": {"name":"ibm-spectrum-scale-csi","namespace":"ibm-spectrum-scale-csi"}, "namespace": "ibm-spectrum-scale-csi", "name": "ibm-spectrum-scale-csi", "reconcileID": "039d73db-9a8b-440b-8eee-68d6f5034bd4"}
panic: reflect: slice length out of range in SetLen [recovered]
        panic: reflect: slice length out of range in SetLen

goroutine 458 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x168b380, 0x1b573f0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
reflect.Value.SetLen({0x1643d60?, 0xc00097fc30?, 0x17ffb40?}, 0x3)
        /usr/local/go/src/reflect/value.go:2334 +0x8d
github.com/presslabs/controller-util/pkg/mergo/transformers.(*TransformerMap).MergeListByKey.func1({0x1643d60?, 0xc00097fc30?, 0x1643d60?}, {0x1643d60?, 0xc00084f578?, 0x0?})
        /go/pkg/mod/github.com/presslabs/controller-util@v0.7.1/pkg/mergo/transformers/transformers.go:181 +0x518
github.com/imdario/mergo.deepMerge({0x1643d60?, 0xc00097fc30?, 0x18e7500?}, {0x1643d60?, 0xc00084f578?, 0x0?}, 0xc00091e730?, 0x1, 0xc000e0ce70)
        /go/pkg/mod/github.com/imdario/mergo@v0.3.15/merge.go:85 +0x30b
github.com/imdario/mergo.deepMerge({0x18e7500?, 0xc00097faf8?, 0x18e7500?}, {0x18e7500?, 0xc00084f440?, 0xc00035c460?}, 0xc000945580?, 0x0, 0xc000e0ce70)
        /go/pkg/mod/github.com/imdario/mergo@v0.3.15/merge.go:94 +0x132a
github.com/imdario/mergo.merge({0x1854140, 0xc00097faf8}, {0x18e7500, 0xc00084f440}, {0xc00091ee18, 0x1, 0xc0004d8d80?})
        /go/pkg/mod/github.com/imdario/mergo@v0.3.15/merge.go:395 +0x32b
github.com/imdario/mergo.Merge(...)
        /go/pkg/mod/github.com/imdario/mergo@v0.3.15/merge.go:319
github.com/IBM/ibm-spectrum-scale-csi/operator/controllers/syncer.(*csiNodeSyncer).SyncCSIDaemonsetFn(0xc000e0c4b0, {0x0, 0x0}, {0x0, 0x0})
        /workspace/controllers/syncer/csi_node.go:174 +0x9db
github.com/IBM/ibm-spectrum-scale-csi/operator/controllers/syncer.GetCSIDaemonsetSyncer.func1()
        /workspace/controllers/syncer/csi_node.go:117 +0x2d
github.com/presslabs/controller-util/pkg/syncer.(*ObjectSyncer).mutateFn.func1()
        /go/pkg/mod/github.com/presslabs/controller-util@v0.7.1/pkg/syncer/object.go:92 +0x63
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.mutate(0xc00097f900?, {{0xc0001458c0?, 0x0?}, {0xc0001458a8?, 0x1b709f0?}}, {0x1b81f00, 0xc00097f900})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/controller/controllerutil/controllerutil.go:339 +0x4f
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.CreateOrUpdate({0x1b709f0, 0xc000138120}, {0x1b77218, 0xc00073c2a0}, {0x1b81f00?, 0xc00097f900}, 0x110?)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/controller/controllerutil/controllerutil.go:211 +0x274
github.com/presslabs/controller-util/pkg/syncer.(*ObjectSyncer).Sync(0xc000beb380, {0x1b709f0, 0xc000138120})
        /go/pkg/mod/github.com/presslabs/controller-util@v0.7.1/pkg/syncer/object.go:60 +0x1b5
github.com/presslabs/controller-util/pkg/syncer.Sync({0x1b709f0?, 0xc000138120?}, {0x1b64110, 0xc000beb380}, {0x0, 0x0})
        /go/pkg/mod/github.com/presslabs/controller-util@v0.7.1/pkg/syncer/syncer.go:97 +0x6b
github.com/IBM/ibm-spectrum-scale-csi/operator/controllers.(*CSIScaleOperatorReconciler).Reconcile(0xc0007c2d40, {0x1b70a60, 0xc000291bf0}, {{{0xc000048f90?, 0x0?}, {0xc000048f78?, 0x40df87?}}})
        /workspace/controllers/csiscaleoperator_controller.go:462 +0x2551
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1b70a60?, {0x1b70a60?, 0xc000291bf0?}, {{{0xc000048f90?, 0x168a800?}, {0xc000048f78?, 0x40fa5d?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00019ad20, {0x1b709b8, 0xc0004802d0}, {0x175fe80?, 0xc000704040?})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323 +0x377
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00019ad20, {0x1b709b8, 0xc0004802d0})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:231 +0x587
```

## Expected behavior
Upgrade should work

### Data Collection and Debugging

Logs has been copied at /u/DUMPS/scale-csi/D.961/

**Comment by Pratibhajoshi** [comment]
I too hit with same issue with both -

1. fresh 518 deployment
2. upgrade to 2.10

```

2023-04-12T09:08:18.113Z        DEBUG   csiscaleoperator_controller.SetStatus   Setting status of CSIScaleOperator is successful
2023-04-12T09:08:18.128Z        DEBUG   csiscaleoperator_controller.Reconcile   Updated resource status.        {"Status": {"versions":[{"name":"ibm-spectrum-scale-csi","version":"2.10.0"}],"conditions":[{"type":"Success","status":"Unknown","lastTransitionTime":"2023-04-12T09:08:17Z","reason":"Unknown","message":""}]}}
2023-04-12T09:08:18.128Z        INFO    Observed a panic in reconciler: reflect: slice length out of range in SetLen    {"controller": "csiscaleoperator", "controllerGroup": "csi.ibm.com", "controllerKind": "CSIScaleOperator", "CSIScaleOperator": {"name":"ibm-spectrum-scale-csi","namespace":"ibm-spectrum-scale-csi"}, "namespace": "ibm-spectrum-scale-csi", "name": "ibm-spectrum-scale-csi", "reconcileID": "103b63e5-ff82-4575-9981-339625eb1b05"}
panic: reflect: slice length out of range in SetLen [recovered]
        panic: reflect: slice length out of range in SetLen

goroutine 493 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x168b380, 0x1b573f0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
reflect.Value.SetLen({0x1643d60?, 0xc00019fc30?, 0x17ffb40?}, 0x3)
        /usr/local/go/src/reflect/value.go:2334 +0x8d
github.com/presslabs/controller-util/pkg/mergo/transformers.(*TransformerMap).MergeListByKey.func1({0x1643d60?, 0xc00019fc30?, 0x1643d60?}, {0x1643d60?, 0xc0003de5b8?, 0x0?})
        /go/pkg/mod/github.com/presslabs/controller-util@v0.7.1/pkg/mergo/transformers/transformers.go:181 +0x518
github.com/imdario/mergo.deepMerge({0x1643d60?, 0xc00019fc30?, 0x18e7500?}, {0x1643d60?, 0xc0003de5b8?, 0x0?}, 0xc000d78730?, 0x1, 0xc000798f30)
        /go/pkg/mod/github.com/imdario/mergo@v0.3.15/merge.go:85 +0x30b
github.com/imdario/mergo.deepMerge({0x18e7500?, 0xc00019faf8?, 0x18e7500?}, {0x18e7500?, 0xc0003de480?, 0xc0001f3500?}, 0x7f897dafa458?, 0x0, 0xc000798f30)
        /go/pkg/mod/github.com/imdario/mergo@v0.3.15/merge.go:94 +0x132a
github.com/imdario/mergo.merge({0x1854140, 0xc00019faf8}, {0x18e7500, 0xc0003de480}, {0xc000d78e18, 0x1, 0xc000c69680?})
        /go/pkg/mod/github.com/imdario/mergo@v0.3.15/merge.go:395 +0x32b
github.com/imdario/mergo.Merge(...)
        /go/pkg/mod/github.com/imdario/mergo@v0.3.15/merge.go:319
github.com/IBM/ibm-spectrum-scale-csi/operator/controllers/syncer.(*csiNodeSyncer).SyncCSIDaemonsetFn(0xc0008008a0, {0x0, 0x0}, {0x0, 0x0})
        /workspace/controllers/syncer/csi_node.go:174 +0x9db
github.com/IBM/ibm-spectrum-scale-csi/operator/controllers/syncer.GetCSIDaemonsetSyncer.func1()
        /workspace/controllers/syncer/csi_node.go:117 +0x2d
github.com/presslabs/controller-util/pkg/syncer.(*ObjectSyncer).mutateFn.func1()
        /go/pkg/mod/github.com/presslabs/controller-util@v0.7.1/pkg/syncer/object.go:92 +0x63
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.mutate(0xc00019f900?, {{0xc000495998?, 0x0?}, {0xc000495980?, 0x1b709f0?}}, {0x1b81f00, 0xc00019f900})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/controller/controllerutil/controllerutil.go:339 +0x4f
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.CreateOrUpdate({0x1b709f0, 0xc000044160}, {0x1b77218, 0xc000518ae0}, {0x1b81f00?, 0xc00019f900}, 0xc000d794a0?)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/controller/controllerutil/controllerutil.go:211 +0x274
github.com/presslabs/controller-util/pkg/syncer.(*ObjectSyncer).Sync(0xc000519a40, {0x1b709f0, 0xc000044160})
        /go/pkg/mod/github.com/presslabs/controller-util@v0.7.1/pkg/syncer/object.go:60 +0x1b5
github.com/presslabs/controller-util/pkg/syncer.Sync({0x1b709f0?, 0xc000044160?}, {0x1b64110, 0xc000519a40}, {0x0, 0x0})

        /go/pkg/mod/github.com/presslabs/controller-util@v0.7.1/pkg/syncer/syncer.go:97 +0x6b
github.com/IBM/ibm-spectrum-scale-csi/operator/controllers.(*CSIScaleOperatorReconciler).Reconcile(0xc0009a52c0, {0x1b70a60, 0xc0004e0840}, {{{0xc000495158?, 0x0?}, {0xc000495140?, 0x40df87?}}})
        /workspace/controllers/csiscaleoperator_controller.go:462 +0x2551
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1b70a60?, {0x1b70a60?, 0xc0004e0840?}, {{{0xc000495158?, 0x168a800?}, {0xc000495140?, 0x40fa5d?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0003966e0, {0x1b709b8, 0xc0002a8cd0}, {0x175fe80?, 0xc0001e4000?})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323 +0x377
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003966e0, {0x1b709b8, 0xc0002a8cd0})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:231 +0x587
[root@api.afm2.cp.fyre.ibm.com scale]#

```

**Comment by Jainbrt** [comment]
This has been fixed in the latest dev build.
